-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- local map = vim.keymap.set
--
-- map("n", "<A-Up>", "<cmd>resize +2<cr>", { desc = "Increase Window Height" })
-- map("n", "<A-Down>", "<cmd>resize -2<cr>", { desc = "Decrease Window Height" })
-- map("n", "<A-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease Window Width" })
-- map("n", "<A-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase Window Width" })
